# Generated by Django 5.1.2 on 2024-10-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentwork',
            name='link',
            field=models.URLField(default='https://example.com'),
        ),
    ]
