# Generated by Django 5.1.2 on 2024-10-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recentwork_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentwork',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
